# Generated by Django 4.2.14 on 2024-08-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suitcaseitem',
            name='category',
            field=models.CharField(choices=[('Essentials', 'Essentials'), ('Toiletries', 'Toiletries'), ('Speciality Clothes', 'Speciality Clothes'), ('Lounge Wear', 'Lounge Wear'), ('Tech', 'Tech'), ('Documents', 'Documents')], default='some-string', max_length=50),
        ),
    ]
