# Generated by Django 4.2.14 on 2024-07-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='location',
            field=models.CharField(default='', max_length=255),
        ),
    ]
