# Generated by Django 4.2.14 on 2024-08-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userinterest_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinterest',
            name='question_1',
            field=models.CharField(choices=[('Plane', 'Plane'), ('Train', 'Train'), ('Car', 'Car'), ('Boat', 'Boat')], default='Plane', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='question_2',
            field=models.CharField(choices=[('Outdoors', 'Outdoors'), ('Relaxation', 'Relaxation'), ('Live Events', 'Live Events'), ('Work', 'Work')], default='Outdoors', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='question_3',
            field=models.CharField(choices=[('Local', 'Local'), ('Fine Dining', 'Fine Dining'), ('Fast Food', 'Fast Food'), ('Vegetarian', 'Vegetarian')], default='Local', max_length=255),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='question_4',
            field=models.CharField(choices=[('Very Often', 'Very Often'), ('Often', 'Often'), ('Once in a While', 'Once in a While'), ('Almost Never', 'Almost Never')], default='Very Often', max_length=255),
        ),
    ]
