# Generated by Django 4.2.14 on 2024-07-31 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userprofile_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 13, 31, 37, 238522)),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 13, 31, 37, 238513)),
        ),
    ]
