# Generated by Django 4.2.14 on 2024-07-31 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_trip_end_date_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 13, 34, 24, 695889)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 7, 31, 13, 34, 24, 695881)),
        ),
    ]
