# Generated by Django 4.2.14 on 2024-08-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='can_edit',
        ),
    ]
