# Generated by Django 4.2.14 on 2024-08-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
