# Generated by Django 4.2.14 on 2024-08-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_itinerary_day_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day',
            field=models.IntegerField(default=1),
        ),
    ]
