# Generated by Django 4.2.14 on 2024-08-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_itinerary_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='location',
        ),
    ]
