# Generated by Django 4.2.14 on 2024-08-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_itinerary_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('packed', models.BooleanField(default=False)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitcase_items', to='main_app.trip')),
            ],
        ),
    ]
