# Generated by Django 4.2.14 on 2024-08-01 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_suitcaseitem_user_alter_suitcaseitem_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suitcaseitem',
            name='trip',
        ),
    ]
