# Generated by Django 4.2.14 on 2024-08-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_suitcaseitem_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='suitcaseitem',
            name='category',
            field=models.CharField(choices=[('Essentials', 'Essentials'), ('Toiletries', 'Toiletries'), ('Speciality Clothes', 'Speciality Clothes'), ('Lounge Wear', 'Lounge Wear')], default='some-string', max_length=50),
        ),
    ]
